### ISSUE TITLE
Packet decryption as of May 2016

### ISSUE THREAD

**Issue by Ousret** [clugh/coc-proxy#11]
Thank @s-a-t-o-r-a-r-e for previous indications ^^
Now I understand better about CoC encryption protocol.

I have some questions regarding coc-proxy code:
- Do we need Blake2s hashing method in case of decryption only ?
- Is CoC Nonce method remain unchanged ?
- How to get NaCl decryption working in simple step ?

Thank you! :)

**Comment by s-a-t-o-r-a-r-e** [comment]
Good afternoon, I'll do my best to answer your questions ^^

> Do we need Blake2s hashing method in case of decryption only ?

BLAKE2 hashing is used to startup both the encryption and decryption streams, so both client and server must implement it in order for things to work properly.

> Is CoC Nonce method remain unchanged ?

The nonce method has remained the same for each successive release of version 8, though it does work _differently_ in comparison to v7, as do the entire encryption and decryption processes. coc-proxy's [current implementation](../blob/master/coc/crypto.py) works perfectly with the actively used nonce-process. It's a great reference for all cryptography concerns.

> How to get NaCl decryption working in simple step ?

This really depends on the environment that you're using, but I wouldn't really say that it's something you do in one 'simple' step, at least not from the ground up. The easiest way would likely be to grab the source from either here, or @FICTURE7's [CocSharp](https://github.com/FICTURE7/CoCSharp) project and just start working away at it, studying their cryptography mechanisms.

If you're not comfortable working with Python or C#, then these two projects would still likely be your best bet, as the method is fairly easy to adapt to other languages, especially those which already have NaCl and BLAKE2 libraries.

It's possible of course to get the crypto setup in a separate language without reference or provided libraries, but that would be a bit far from simple. You probably don't want to be like me and end up writing complete translations for everything in completely procedural code, having to port over BLAKE2b and NaCl to the oddities of a certain language ;3

**Comment by Ousret** [comment]
Hi!

I really appreciate your help.
Now I can understand and begin to create my own python module.

Thank again!^^

**Comment by s-a-t-o-r-a-r-e** [comment]
Awesome, I'm glad I was able to help!

If you need any further help, feel free to just leave me a mention with @s-a-t-o-r-a-r-e, and I'll do my best to respond within a timely manner.

**Comment by djsmax** [comment]
@s-a-t-o-r-a-r-e, hello. Can I also ask you a question?)
I do not understand very much in the CoC encryption, so the question may seem a bit strange ..)
I'm trying to implement CoC client. I use this [wiki](https://github.com/clugh/cocdp/wiki/Protocol), and a [proxy](https://github.com/clugh/coc-proxy) written in py3. Advances ended at step 5 .. There are some ideas realization of the client?

**Comment by s-a-t-o-r-a-r-e** [comment]
@djsmax, your reply really should have gone into a separate issue, though I'll try to help you here...

Honestly though, you've provided very little information regarding your setup so it's quite difficult to actually know what's gone wrong.

If you're simply not receiving the 20104 packet after sending your 10101, then it's likely that you've built a malformed packet. Make sure _especially_ that you have properly prefixed the stream with the needed nonce and key.

If you are receiving a reply packet, but it's not 20104 (rather, it's 20103 or something else), then you've simply botched your login credentials. Make sure that your userId and token are correct.

May I ask what exactly your motive is for making yet another Clash client? It seems rather superfluous, and it's rather ironic asking for help fixing what seems to be a closed-source project in this context.

**Comment by djsmax** [comment]
@s-a-t-o-r-a-r-e , thank you for fast reply) the problem is I can't send 10101 (client_login) packet. This packet requires to be prefixed with snonce (randombytes - 1) in accordance with clugh's doc wiki. Can you tell me size of this nonce and any method to generate it on python? I noob in network protection and decryption,so i can't understand some of termins completely.
Target of this work.. It's just for education..)
P.S. sorry for my bad English..

**Comment by s-a-t-o-r-a-r-e** [comment]
@djsmax, the `snonce` bit is generated simply with a call to TweetNaCl's `randombytes` function, with a length of 24-bytes.

Below is some code showing a bit of how my client emulator constructs the Login message (10101). It should be easy to adapt over to Python, especially since only a TweetNaCl lib is really needed to supplement the already existing standard libs.

``` javascript
var crypto, combinedKeys, nonce
crypto = client.crypto
crypto.generateClientKeyPair()
crypto.generateClientNonce()

combinedKeys = crypto.ckeyPublic + crypto.skeyPublic   // array concatenation
nonce = Crypto.hash(combinedKeys)   // used later, for TweetNaCl.crypto_box(...)

msg.putBytes(crypto.serverRandom)
msg.putBytes(crypto.clientNonce)
```

Here, `msg` is the packet-output stream, `crypto` is the client's crypto instance, while `Crypto` is the entire cryptography namespace (providing useful functions like `hash(...)`, etc.

Most important, `crypto.serverRandom` is the 24-byte array received from 20100, while `crypto.clientNonce` is the `randombytes(...)` value, also called `snonce` in clugh's doc.

The exact details of the `clientNonce` generation are very simple, built using `generateClientNonce()`:

``` javascript
this.clientNonce = byte(24)
TweetNaCl.randombytes(this.clientNonce, 24)
```

That's about it! Though, just a word of warning here: if this bit is complex for you, then you're not going to have a good time later on with client-emulator work. I suggest instead working your way up to this level over time, and maybe coming back then once you're more familiar with encryption, reversing, and packet analysis.

Sorry for the late reply (needed sleep ^^"),
~ Satori

**Comment by djsmax** [comment]
@s-a-t-o-r-a-r-e, thank you very much)) now I can send & receive messages btw client&server. And now the latest question: how about sending protocol commands? Commands described `[here](https://github.com/clugh/cocdp/wiki/Protocol-Commands) ,but for send their, special checksum required. Can I calculate the hash manually or this isn't really? 
Thank you very much)))

**Comment by s-a-t-o-r-a-r-e** [comment]
@djsmax, yes you can calculate the hash manually, though it requires in-depth tracking of the complete client state. It's not too difficult to reverse yourself though, so I'll have no part in spoon-feeding the information across to anyone else, especially for a private project.

**Comment by djsmax** [comment]
@s-a-t-o-r-a-r-e,anyway,thank you for help for me) now I can sum all this up,and verdict : CoC client is a bad idea.)
Thank you so much again for improving me ;)
