### ISSUE TITLE
Keys and offsets needed for version 8.551.4

### ISSUE THREAD

**Issue by waqasrana** [clugh/coc-proxy#15]

**Comment by ghost** [comment]
@s-a-t-o-r-a-r-e ?

**Comment by s-a-t-o-r-a-r-e** [comment]
@knightking10, thanks for the mention, as it's the only way I'll see these ^^!

The new key for v8.551.4 is `349ce78b78a06a4e94645435acba1dfffc40cc2276558ed2d118f1343a197876`

**Android Offsets: (for v8.551.4)**
ARMv7: 0x47c020
x86: 0x6f2020

**iOS Offsets: (for v8.551.2, as .4 hasn't shipped yet here – same key though)**
ARMv7: 0x80af58
ARM64: 0x11bcac4

**Server Version Info: (as returned from headless client)**
Datahash/Masterhash: 15a028794a182570a59e7c351e21d5145bb35614
Version: 8.551.7

**NOTE:**
Interestingly enough, the key-version for this key has changed up a little bit. It's jumped from version 9 to 14. Nothing super significant here though, as SC was likely just playing around with things before official release.

The encryption method remains the same: only the key must be updated for a proxy to work just fine.

Further, certain packet structures have changed a bit to accommodate for this version's changes, though they're nothing massive. Any headless client or private server software must account for these structural changes in order to function.

**Comment by s-a-t-o-r-a-r-e** [comment]
Also, I realize I've posted offsets in base-10 in the past, rather than hex (in conformance with the wiki-style here), so I'll add those here:

**Android:**
armv7: 4702240
x86: 7282720

**iOS:**
armv7: 8433496
arm64: 18598596

**MD5 - Android:**
armv7: 532b6221bcbd6b0361efdd45b926576c
x86: a40f0da23aba7d562bcd6aaf9f13e1e0

**MD5 - iOS:**
combined: cc6dcb687ee29c380a2320d5fb6f0c60    (both arm64 and armv7 live in the same binary on iOS)

Again, listed iOS information is for 8.551.2, while Android is for the slightly higher version 8.551.4. The key is the same for both versions. In fact, it would be unlikely for the key to change across 8.551.\* releases. Offsets and MD5s will vary by version, of course.

**Comment by BerkanYildiz** [comment]
@knightking10 😂  😂 

![UCLess](http://www.mememaker.net/static/images/memes/4284879.jpg)

**Comment by OMGItssCrayCray** [comment]
LOL

**Comment by pochupin** [comment]
thanks @s-a-t-o-r-a-r-e

**Comment by OMGItssCrayCray** [comment]
@s-a-t-o-r-a-r-e Any chance you could add me on skype? omgitsscraycray
Thanks 
~CrayCray

**Comment by s-a-t-o-r-a-r-e** [comment]
@OMGItssCrayCray, added.

**Comment by knightking10** [comment]
@s-a-t-o-r-a-r-e thank you.Could you add me too?knight.king584 (skype)

**Comment by waqasrana** [comment]
thankyou for your help

**Comment by knightking10** [comment]
ok

**Comment by goldbi** [comment]
@s-a-t-o-r-a-r-e @waqasrana Can i get your skype as well? 
hiimeiffel
Eiffel, From Ultrapowa Community.

**Comment by BerkanYildiz** [comment]
@goldbi , What will you do ? Tell him your owning a nice community with nice people ? :joy:
