### ISSUE TITLE
New coc update v9?

### ISSUE THREAD

**Issue by knightking100** [clugh/coc-proxy#20]
I'm pretty sure that the key is 44505d9838bf6727beaa7b733242d823ed4e1cea4966ad2892964720f883e900
But when i try with the proxy, I didn't get login OK, seems the crypto has changed. Any ideas about this?

**Comment by zzVertigo** [comment]
Cheeky bastards at Supercell.

**Comment by knightking100** [comment]
@s-a-t-o-r-a-r-e?

**Comment by zyxwvuts** [comment]
I'm trying to remember how to get a functioning debugger running from back when we worked on this for the TH11 update.  It looks like we still send 10100 in the same format and receive a 28-byte 20100.  I'm guessing the logic to calculate the nonce changed or something like that.  Clugh was the man with the last update.  Hopefully he's still around and motivated enough to work his magic.

**Comment by zzVertigo** [comment]
He was around a while ago on the UCS forums asking about the proxies and getting banned sooooooooo lets cross our fingers.

**Comment by BerkanYildiz** [comment]
Even if the key is patched, you can still play on the official server. IT IS NOT supposed to happen.
Means either the client is generating the key and server is knowing it somehow, or the key (we are patching) is not used at all.

Afaik, it's still Sodium because of the 16 bytes padding in 10108.

**Comment by zyxwvuts** [comment]
Good catch.  Seems like instead of just having it as a single string in memory that they could break it up into several strings that they concatenate together.  Or they could probably generate the string from just an integer if they felt like getting fancy.  In either case, it will probably take going through this with a decompiler and/or debugger.  I'm still working to get mine set up and having zero luck so far.

**Comment by knightking100** [comment]
@clugh
Are you here?

**Comment by spAnser** [comment]
Patching they key doesn't let the game connect to the liver server anymore.

**Comment by BerkanYildiz** [comment]
> "Patching they key doesn't let the game connect to the liver server anymore."

Wroooooooooooooooong

**Comment by FICTURE7** [comment]
@spAnser Using a pseudo-code generator can really help a lot.

**Comment by spAnser** [comment]
@BerkanYildiz My patched version fails to login

**Comment by BerkanYildiz** [comment]
@spAnser My patched version success to login

**Comment by BerkanYildiz** [comment]
> Even if the key is patched, you can still play on the official server. IT IS NOT supposed to happen.

> Good catch. Seems like instead of just having it as a single string in memory that they could break it up into several strings that they concatenate together.

**Comment by spAnser** [comment]
My patched version acts weird if I use the proxy and skip the decrypt and encrypted phase it logs in if I don't use a proxy at all it fails to login.

**Comment by BerkanYildiz** [comment]
I never tried without proxying. I'm using my proxy without encrypting / decrypting messages, just resending them.

**Comment by zyxwvuts** [comment]
@OMGItssCrayCray Cray cray, you mentioned on another site that you cracked the encryption.  You plan to share that?

**Comment by BerkanYildiz** [comment]
@zyxwvuts 

![image](https://cloud.githubusercontent.com/assets/15068742/26521576/10870442-42ec-11e7-9e64-747d86d51e39.png)

**Video :** 
[![CoC 9.x - Comming Soon](https://i.imgur.com/fEWIOOm.jpg)](https://2.sendvid.com/djx5294c.mp4 "CoC 9.x - Comming Soon")

**Comment by BerkanYildiz** [comment]
[http://2.sendvid.com/djx5294c.mp4](http://2.sendvid.com/djx5294c.mp4)

**Comment by zyxwvuts** [comment]
That's really cool Berkan.  How does the encryption algorithm work?

**Comment by zzVertigo** [comment]
Yeah @zyxwvuts we got it working on our side. Although I am un sure of how my developer actually did it xD

**Comment by BerkanYildiz** [comment]
@zyxwvuts What CrayCray means, is that no one will tell you how the crypto is working.

**Comment by zzVertigo** [comment]
-_-

**Comment by zyxwvuts** [comment]
Oh, ok, maybe you should go to braghub.com to post your screenshots, then.  This is github where people share source.  You were trying to get clugh to share his work with you but you refuse to share your work.  Shameful, but you're welcome to be that way.  Cheers.

**Comment by BerkanYildiz** [comment]
@zyxwvuts 

![image](https://cloud.githubusercontent.com/assets/15068742/26525321/91d12f56-4354-11e7-9521-556112adde34.png)
![image](https://cloud.githubusercontent.com/assets/15068742/26525322/96129b22-4354-11e7-83bf-34a013d06898.png)

**Comment by FICTURE7** [comment]
You're probably still using the legacy RC4 crypto which is still in the game.

**Comment by zyxwvuts** [comment]
I'll bet all the people who do easy things like creating software for self-driving vehicles or developing world-champion-beating Go software are really jealous of you, too.  I mean, heck, you took a project that other people had done 99% of the work and figured out the remaining 1%.  I know I'm amazed.  Kudos to you.

**Comment by BerkanYildiz** [comment]
I'm the first one who made a CR Seeeerver, BUT ANYWAY. I'm apparently taking stuff from everyone, and "figuring out the remaining 1%".. Oh boy, you don't know what's going on here. Braaaaaainwashed. Why do everyone think i will just hand out shit bahaha.

Anyway, if i'm apparently taking shit from everyone, why don't you start IDA or whatever debugging/disassembling software you have, and analyze the library ? I mean, it's easy to say blabla you don't help u cunt, but, why don't you do it yourself then ?

I know, i'm awesome... I'm so jealous of myself.

**Comment by zzVertigo** [comment]
Ladies.. Ladies.. Your both beautiful. No more of this :)

**Comment by BerkanYildiz** [comment]
Funny for someone posting screenshots of his emulator with a little "GL.Servers.CoC" behind.

**Comment by zyxwvuts** [comment]
I guess you're saying "brainwashed" because of some disagreement you have with some other private server developer.  I don't have a clue if you copied them or not and honestly couldn't care less because sticking a database backend on top of the communication piece is trivial.  I'm talking about you gladly taking the work that clanner, clugh, and others have done in the past and then being unwilling to contribute the small piece of that large puzzle you have figure out.  That doesn't make you awesome.

Personally, cracking the encryption isn't worth the hundreds of dollars to purchase a disassembly tool like IDA.

**Comment by BerkanYildiz** [comment]
I will be honest here, it's like an opportunity for me to shutdown every other private server, because of the amount of money to earn, which is.. questionable.

"Business is business.."

**Comment by spAnser** [comment]
@BerkanYildiz So you are openly admitting to making money off of Supercell IP and plan to attempt to make more by not sharing and letting the others shutdown so more people drive to your private server for profits? I think that might be a very questionable discussion for GitHub.

**Comment by BerkanYildiz** [comment]
@SpAnser, exactly !

**Comment by zzVertigo** [comment]
L M A O

**Comment by goldbi** [comment]
Don't worry Server Owners, ultrapowa.com is still with you! have faith. 
You know all who is the bad guy here, keep trust in us! ;)
Bye.

**Comment by zzVertigo** [comment]
"Trust"

**Comment by aididhaiqal** [comment]
@goldbi you will have coc serve that support 9.24,like 9 month from now

**Comment by DarkSoulCoC** [comment]
@goldbi lemme correct your statement "dont worry rich server owners, ultrapowa.com is still only with you. Starting is price only $15 for 500 players" HECK MEN

**Comment by BerkanYildiz** [comment]
@goldbi, indeed, we all do know who is the bad guy here :).

**Comment by zzVertigo** [comment]
Hint: Starts with a 'g' and ends with an 'i'

**Comment by zyxwvuts** [comment]
People are on this site because they are coders and have written whatever clash tools they might find useful.  Nobody here gives an F about which private server developer did what unless that developer plans to share source.  You guys go argue about this on your own sites.

**Comment by zzVertigo** [comment]
You don't know the backstory to this.

**Comment by BerkanYildiz** [comment]
You don't know the backstory to this.

**Comment by zyxwvuts** [comment]
I do... I've been running my tools since Clash was first released  This just isn't the proper forum for such a discussion.  It's github - a place for sharing source.

**Comment by BerkanYildiz** [comment]
![image](https://media.giphy.com/media/3v1Sz0oTKRsly/giphy.gif)

**Comment by zyxwvuts** [comment]
So is it right that you guys just disabled the packet encryption (or use your own) and can just communicate with your private server but not the SC server?

**Comment by aididhaiqal** [comment]
@zyzwvuts,We have a way to communicate with supercell server

**Comment by waqasrana** [comment]
which is...?

(p.s: everyone ignore the trolls/tards)

**Comment by BerkanYildiz** [comment]
@waqasrana, no one will tell you..

**Comment by zzVertigo** [comment]
lol

**Comment by zyxwvuts** [comment]
For anybody who cares about how berkan/craycray/aidid "cracked" the v9 encryption, they modified the USE_PEPPER_CRYPTO value from true to false in client_globals.csv.  This apparently causes the client to send/receive packets encrypted using the old RC4 encryption.  

None of that is really useful for the people who are watching this thread and want to create a MITM proxy to the actual server, but I thought I would mention it in case it gives anybody some ideas (and also because they have been such horses' asses in this thread).  I'm sure the other makers of private servers have figured this out (as the flag in client_globals.csv has been in there all through v8), but just in case they haven't, there it is.  Whew, now they can't "shutdown all the other private servers" and monopolize the huge private server market, making tens of dollars per year.

**Comment by aididhaiqal** [comment]
But hey,You still need packet dump

**Comment by zyxwvuts** [comment]
People here are used to decoding changes to packets in each release.  I've sat MITM to the BL server and captured all the relevant packets that you guys have manged to (sort of) produce.  Folks who care about making private servers instead of proxies could do the same.  Speaking of which, the BL RC4 nonce and initialization bytes are customized a little.  If anybody is interested in MITM to the BL server, I can post the relevant details.  

I'll wait until I can talk to an official server to put too much work into packet defs.

**Comment by aididhaiqal** [comment]
So you figured our rc4 key haha,anyway PM me on discord at  Vicky#1413

**Comment by BerkanYildiz** [comment]
Ahahahah

**Comment by FICTURE7** [comment]
If you want to get some dumps from the official server, use a custom client with an old key version however make sure you're telling the server that you're using the latest version with the latest master hash. It should allow you to login and produce some dumps. Surprisingly.

You can always open up libg.so in IDA and figure out the structs from there as well.

**Comment by aididhaiqal** [comment]
PM if you need help

**Comment by Makita43** [comment]
This "Issue" is funny.

**Comment by zyxwvuts** [comment]
What methods are people using to get IDA running against this?  x86 or ARM?  Any emulators that are debuggable?  I've gotten it to attach to a process running on a physical ARM device , but IDA (at least version 6.8) doesn't support breakpoints on ARM devices.  I figured the general idea would be to drop a breakpoint when the RC4 key address is read (I would switch it to RC4 mode where I know the key's address) and then walk the stack backwards to find where it branches from the "normal" encryption to RC4.

**Comment by zzVertigo** [comment]
This is so cute. Anyways, who cares if we didn't solve the 9.x crypto (aka Sodium part of it). We were the first people to support it lol. People who act like this are just plain jealous of us (BarbarianLand and Gobelinland) because we produce some quality servers with the latest support.

Quit your crying and complaining and get the fuck off our servers with your proxies.

**Comment by zzVertigo** [comment]
Also @knightking100 can we close this useless issue. Its going no where at this point.

**Comment by BerkanYildiz** [comment]
> Whew, now they can't "shutdown all the other private servers" and monopolize the huge private server market, making tens of dollars per year.

Well, actually, it's more like tens of dollars per hour.
And we will still monopolize the huge private server market, don't worry about that :).


![image](https://media.giphy.com/media/94EQmVHkveNck/giphy.gif)

**Comment by smartclash** [comment]
Agree @knightking100 @OMGItssCrayCray @BerkanYildiz

**Comment by smartclash** [comment]
I am just thinking of @clugh 's mail inbox. It might had been spammed by GitHub notifications. lol. Thanks to brainless people over here

**Comment by zzVertigo** [comment]
lmao true. Just alone in my inbox 51 new messages.

**Comment by zzVertigo** [comment]
Anyways. We still have it either way without solving the newest crypto because @aididhaiqal is a god and figured out magical BL ways to do it. So @zyxwvuts you only solved maybe 25% of how we did it. Congratulations.

https://discord.gg/Nu675nd

**Comment by BerkanYildiz** [comment]
@OMGItssCrayCray Well, it's actually very easy, but people here are actually retards, means they can't do shit themselves and keep begging for hints / code.


![Triggered](https://media.giphy.com/media/vk7VesvyZEwuI/giphy.gif)

**Comment by zzVertigo** [comment]
xD

**Comment by knightking100** [comment]
Issue closed due to some 'useless' messages

**Comment by smartclash** [comment]
lol @knightking100
